### ISSUE TITLE
RunningFolder with a . (dot) in the foldername

### ISSUE THREAD

**Issue by marienho** [andreabbondanza/vscode-iisee#2]
Hi,

Thank you for writing this great extension! 
We use it all the time and have only run into one problem: when the RunningFolder contains a . (dot) IISExpress ignores the entire folder and shows the content of the parent folder.

Here is an example: I have a project located in c:\projects\foo.bar

When I run the start server command a site is added to the applicationHost.config of IIS Express with a physicalPath of c:\projects

Hope you can fix this some time. Many thanks in advance!

**Comment by andreabbondanza** [comment]
Hi,
Thank you for the report, I'll check it soon as possible!

Have a nice day,

Andrew

**Comment by andreabbondanza** [comment]
Hi marienho,
I've fixed the problem and tested and it works fine now with dotted folders.
I've also already published the update on the store.
Please if you have some other issue about this let me know.

Thank you for the support!,

Andrew

**Comment by marienho** [comment]
Awesome Andrew! Thanks a lot! Have already updated the extension and tested it. Works great!
