### ISSUE TITLE
Minor typo: "ISS" should be "IIS"

### ISSUE THREAD

**Issue by JeffJacobson** [andreabbondanza/vscode-iisee#3]
The abbreviation _IIS_ is sometimes misspelled as _ISS_ in some of the commands. (See screenshot below.)

Everything is still completely usable, so it is not that big of a deal.

![iss](https://cloud.githubusercontent.com/assets/713754/23440162/312d9632-fdcf-11e6-8817-89868ecd97f6.png)

**Comment by andreabbondanza** [comment]
Ahah thanks for the tips.

Probably I was thinking about the International Space Station that time [😊]


Andrea Vincenzo Abbondanza

[1485879885584_rsz_logox2.png]
Dew Studio di Andrea Vincenzo Abbondanza
Via Nazionale delle Puglie, 7
Casalnuovo di Napoli, 80013
Tel: +39 081 1891 8232
Mail: info@dewstudio.eu | andrea@dewstudio.eu
Web: https://www.dewstudio.eu<http://www.dewstudio.eu>
-

Ai sensi del D.Lgs.196/2003 "Codice in materia di trattamento dei dati personali" si precisa che le informazioni contenute in questo messaggio possono essere riservate ed a uso esclusivo del destinatario. E' vietato a soggetti diversi dallo stesso qualsiasi uso, copia, inoltro o diffusione di quanto in essa contenuto. Qualora questa comunicazione Vi fosse pervenuta per errore, Vi invitiamo a cancellarla dal Vostro sistema dandocene gentilmente comunicazione. Grazie.

Confidentially notice. This e-mail transmission may contain legally privileged and/or confidential information. Please do not read it if you are not the intended recipient. Any use, distribution, reproduction or disclosure by any other person is strictly prohibited. If you have received this e-mail in error, please notify the sender and destroy the original transmission and its attachments without reading or saving it. Thank you.
-
https://www.linkedin.com/pub/andrea-vincenzo-abbondanza/3b/354/6ab
________________________________
Da: Jeff Jacobson <notifications@github.com>
Inviato: mercoledì 1 marzo 2017 01.05.22
A: andreabbondanza/vscode-iisee
Cc: Subscribed
Oggetto: [andreabbondanza/vscode-iisee] Minor typo: "ISS" should be "IIS" (#3)


The abbreviation IIS is sometimes misspelled as ISS in some of the commands. (See screenshot below.)

Everything is still completely usable, so it is not that big of a deal.

[iss]<https://cloud.githubusercontent.com/assets/713754/23440162/312d9632-fdcf-11e6-8817-89868ecd97f6.png>

**Comment by andreabbondanza** [comment]
Fixed, thank you!
