### ISSUE TITLE
Selecting Edge from "Select the Browser" seems to just open default browser, instead of Edge

### ISSUE THREAD

**Issue by JeffJacobson** [andreabbondanza/vscode-iisee#5]
Steps to reproduce
-------------------

1. Set the default browser for Windows to a browser other than Edge. (System Settings > Default App Settings)
2. Open Visual Studio code.
3. In the command palette (Ctrl + Shift + P), Select *IIS-EE: Select the browser*, then select *Edge*.
4. From the command palette, select *IIS-EE: Start IIS Express Server*. Instead of opening Edge, whatever you set the default browser to in step 1 will open instead.

Workaround
-------------

One of the following
* Change the default browser setting in Windows to Edge
* When the default (non-Edge) browser opens, copy the URL from that browser, open Edge, then paste the URL into Edge.

### OS ###
Microsoft Windows 10 Enterprise
Version 10.0.15063 Built 15063

### Edge ###
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Comment by andreabbondanza** [comment]
Thank you for the tips. I'll check ASAP.

**Comment by JeffJacobson** [comment]
FYI, I've just learned that this issue might not be with the extension, but with how my agency has our computers configured. If you are unable to reproduce the error then you should probably assume the extension is working and close the issue.

Background: In another project I am working on, I just learned that the way our agency has something configured breaks some sites in Edge that work correctly for the general public when they are also using Edge. (I don't know specifically how the configuration differs here, though.)

**Comment by andreabbondanza** [comment]
Hi Jeff, honestly I'm a bit full of projects at work and I still didn't had the opportunity to check the code. For this I'm glad to see that the problem isn't the extension (I hate when I don't have the time to fix my bug :| ).
However I can't say anything else that a thank you for your support and interest about this.
